version: '2'
services:
  nginx:
    image: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html/
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - node
  node:
    build: "./node"
    # ports:
    #   - "3000:3000"
    volumes:
      - ./node:/node
    depends_on:
      - mongo
#  db:
#    image: mysql
#    environment:
#        MYSQL_ROOT_PASSWORD: otyanoko
#        MYSQL_DATABASE: data
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  mongo:
    image: mongo:latest
    volumes:
      - ./data_mongo:/data/db

    # ports:
    #   - "27017:27017"
