version: '2'
services:
  nginx:
    image: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html/
#  db:
#    image: mysql
#    environment:
#        MYSQL_ROOT_PASSWORD: otyanoko
#        MYSQL_DATABASE: data
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
